run:
  timeout: 5m
  go: '1.25'

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gocritic
    - gosec
    - bodyclose
    - noctx
    - sqlclosecheck

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    check-shadowing: true
  
  gofmt:
    simplify: true
  
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  
  gosec:
    excludes:
      - G404  # Use of weak random number generator

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
